#!/bin/bash
# mkalieniso - makes an Alien themed iso

RELENG_PROFILE=master
LOCAL_PROFILE=profile

if [[ $EUID -ne 0 ]]; then
	echo This script must be run as root.
	exit 1
fi

rm -rf $LOCAL_PROFILE
mkdir $LOCAL_PROFILE
cp -r $RELENG_PROFILE/* $LOCAL_PROFILE

# CUSTOMIZATIONS HERE?

cd $LOCAL_PROFILE
mkdir out
./build.sh -v
